import { flatten } from 'lodash/array';

class Ec2InstancesService {
    constructor(credentials) {
        this.credentials = credentials;
    }

    getInstances() {
        return flatten([ [ { Type: 't2.nano',
            SubnetId: 'subnet-e89081b5',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.large',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' },
          { Type: 't2.large',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 'm4.large',
            SubnetId: 'subnet-2a98eb77',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'stopped' } ],
        [ { Type: 't2.large',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.nano',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' },
          { Type: 't2.nano',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.nano',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' },
          { Type: 't2.nano',
            SubnetId: 'subnet-e79c8fc8',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.nano',
            SubnetId: 'subnet-ada0d3f0',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.large',
            SubnetId: 'subnet-e89081b5',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.large',
            SubnetId: 'subnet-e89081b5',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ],
        [ { Type: 't2.nano',
            SubnetId: 'subnet-e89081b5',
            VpcId: 'vpc-9f8e52f8',
            Tags: [Array],
            State: 'running' } ] ])
    }
}

export default Ec2InstancesService;